# {{ $ids := "oe_graphql_base" }}ids: {{ $ids }}
# {{ $org := "oxid-esales" }}organisation: {{ $org }}
# {{ $name := "graphql-base" }}name: {{ $name }}
# {{ $repo := "OXID-eSales/graphql-base-module" }}repo: {{ $repo }}

install:
    cache:
        prepared_shop: false
    git:
        repository: '{{ $repo }}'
        ref: &ref '{{ .Github.RefName }}'
        shop_url: 'https://github.com/OXID-eSales/graphql-base-module.git'
        shop_ref: *ref
    composer:
        transform: |
            {
                "require": {
                    "oxid-esales/oxideshop-ce": "{{ .Data.global.composer.dev_ref }}",
                    "oxid-esales/twig-component": "{{ .Data.global.composer.dev_ref }}",
                    "oxid-esales/twig-admin-theme": "{{ .Data.global.composer.dev_ref }}",
                    "oxid-esales/apex-theme": "{{ .Data.global.composer.dev_ref }}",
                    "oxid-esales/developer-tools": "{{ .Data.global.composer.dev_ref }}"
                }
            }
    custom_script_container: |
        perl -pi -e 'print "SetEnvIf Authorization \"(.*)\" HTTP_AUTHORIZATION=\$1\n\n" if $. == 1' source/.htaccess

        vendor/bin/oe-console oe:database:reset --db-host=mysql --db-port=3306 --db-name=example --db-user=root --db-password=root --force
        vendor/bin/oe-console oe:module:install ./

        vendor/bin/oe-eshop-doctrine_migration migrations:migrate
        vendor/bin/oe-eshop-db_views_generate

        vendor/bin/oe-console oe:module:activate "{{ $ids }}"
        vendor/bin/oe-console oe:theme:activate apex

install_shop_with_modules:
    composer:
        root_url: ''

runscript: &runscript
    matrix:
        script: |
            [
              "graphql_base:tests-unit",
              "graphql_base:tests-integration",
              "graphql_base:tests-codeception"
            ]
    composer:
        early: true
    graphql_base:
        path: ''

runslim:
    <<: *runscript
    matrix:
        script: |
            [
              "graphql_base:phpcs",
              "graphql_base:phpstan",
              "graphql_base:phpmd"
            ]

sonarcloud:
    matrix:
        testplan: '["-"]'
    strip_path: '/var/www/'
    project_key: 'OXID-eSales_graphql-base-module'
    project_name: '{{ $org}}/{{ $name }}'
    parameters: |
        -Dsonar.language=php \
        -Dsonar.scm.provider=git \
        -Dsonar.sources=src \
        -Dsonar.tests=tests

finish:
    slack_title: '{{ print $name }} ({{ .Data.global.git.shop_ref }}) by {{ .Github.Actor }}'
