name: Trigger schema workflow for graphql base

on:
    push:
        tags:
            - v5.0.*
            - v5.1.*
            - v5.2.*
            - v6.0.*

jobs:
    documentation_schema:
        runs-on: ubuntu-latest
        steps:
            - name: Set documentation branch for 5.0
              if: startsWith(github.event.ref, 'refs/tags/v5.0')
              run: |
                echo "DOCUMENTATION_BRANCH=5.0-en" >> $GITHUB_ENV

            - name: Set documentation branch for 5.1
              if: startsWith(github.event.ref, 'refs/tags/v5.1')
              run: |
                echo "DOCUMENTATION_BRANCH=5.1-en" >> $GITHUB_ENV

            - name: Set documentation branch for 5.2
              if: startsWith(github.event.ref, 'refs/tags/v5.2')
              run: |
                echo "DOCUMENTATION_BRANCH=5.2-en" >> $GITHUB_ENV

            - name: Set documentation branch for 6.0
              if: startsWith(github.event.ref, 'refs/tags/v6.0')
              run: |
                echo "DOCUMENTATION_BRANCH=6.0-en" >> $GITHUB_ENV

            - name: Trigger schema generation in documentation
              uses: convictional/trigger-workflow-and-wait@v1.6.5
              with:
                  owner: oxid-esales
                  repo: oxapi-documentation
                  github_user: ${{ secrets.CI_USER }}
                  github_token: ${{ secrets.GH_CI_JENKINS_TOKEN }}
                  workflow_file_name: schema.yml
                  ref: ${{ env.DOCUMENTATION_BRANCH }}
