name: Schedule for graphql base module

on:
    schedule:
        - cron: '0 0 */7 * *'

jobs:
    p81m57both:
        name: 'Php-8.1-Mysql-5.7'
        uses: ./.github/workflows/development.yml
        secrets: inherit
        with:
            php: '8.1'
            mysql: '5.7.37'
