name: Auto trigger on push or pull requests

on:
    pull_request: {}
    push: {}

jobs:
    call_matrix:
        uses: OXID-eSales/github-actions/.github/workflows/universal_workflow_light.yaml@v4
        with:
            testplan: '~/defaults/8.0.x.yaml,~/defaults/php8.3_mysql8.0_only.yaml,~/graphql-base.yaml'
            runs_on: '"ubuntu-latest"'
            defaults: 'v4'
            plan_folder: '.github/oxid-esales'
        secrets:
            DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
            DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
            CACHE_ENDPOINT: ${{ secrets.CACHE_ENDPOINT }}
            CACHE_ACCESS_KEY: ${{ secrets.CACHE_ACCESS_KEY }}
            CACHE_SECRET_KEY: ${{ secrets.CACHE_SECRET_KEY }}
            enterprise_github_token: ${{ secrets.enterprise_github_token }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
